engines:
  csslint:
    enabled: false  
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - python
      - php
  eslint:
    enabled: false  
  fixme:
    enabled: false
  radon:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "tests/"
- "spec/"
- "**/vendor/"
- "static/"
- "sas/booking/tests.py"
- "sas/user/tests.py"
- "sas/sas/basic.py"
- "sas/user/management/commands/prepare.py"
