language: python

python:
  - "3.4"
  - "3.5"

sudo: required
disty: trusty

# command to install dependencies
before_install:
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i --force-depends google-chrome*.deb
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
before_script:
    - "export DISPLAY=:99.0"
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
    - sleep 5
# command to run tests
script:
    - cd sas
    - python manage.py makemigrations user booking
    - python manage.py migrate
    - coverage run manage.py harvest -v 2
    - python manage.py test

after_success:
  coveralls

after_script:
    - python manage.py test test_pep8
